# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "intern-terragrunt-states-dev-backend"
    dynamodb_table = "intern-terragrunt-states-dev-backend"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
